# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Starman < Formula
  desc "CLI tool for managing GitHub starred repositories with AI — sync, analyze, categorize, search, and generate awesome lists"
  homepage "https://github.com/morehao/starman"
  version "0.0.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/morehao/starman/releases/download/v0.0.14/starman_0.0.14_darwin_amd64"
      sha256 "5e2d4c36436548300bb459761d56c3410c22976e4c2f36961f27785f04e9a30b"

      define_method(:install) do
        bin.install "starman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/morehao/starman/releases/download/v0.0.14/starman_0.0.14_darwin_arm64"
      sha256 "1b6f2d33fd872ce3b142e60469287357ba26b798775cc1ce6e6024b1b34de669"

      define_method(:install) do
        bin.install "starman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/morehao/starman/releases/download/v0.0.14/starman_0.0.14_linux_amd64"
      sha256 "51e5c37fd7ff6e5ff6f48a0ee9b7183d7cbc447985ba525fd8a95f3c885bf42d"
      define_method(:install) do
        bin.install "starman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/morehao/starman/releases/download/v0.0.14/starman_0.0.14_linux_arm64"
      sha256 "f062dc6f69e1c23c3c4ba527a5327d1a1e4dbf37d78175d323b9649ad6208045"
      define_method(:install) do
        bin.install "starman"
      end
    end
  end

  test do
    system "#{bin}/starman --version"
  end
end
